title = "AdeebaMirza"
baseURL = "https://example.com/"
defaultContentLanguage = "en"
hasCJKLanguage = false
defaultContentLanguageInSubdir = false
removePathAccents = true
enableGitInfo = false
summaryLength = 30
paginate = 10
enableEmoji = true
enableRobotsTXT = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = [
  "\\.ipynb$",
  ".ipynb_checkpoints$",
  "\\.Rmd$",
  "\\.Rmarkdown$",
  "_cache$"
]
disableAliases = true
timeout = 600_000

[permalinks]
event = "/talk/:slug/"
tags = "/tag/:slug/"
categories = "/category/:slug/"
publication_types = "/publication-type/:slug/"

[outputs]
home = [
  "HTML",
  "RSS",
  "JSON",
  "WebAppManifest",
  "headers",
  "redirects"
]
section = [ "HTML", "RSS" ]

[imaging]
resampleFilter = "lanczos"
quality = 75
anchor = "smart"

[taxonomies]
tag = "tags"
category = "categories"
publication_type = "publication_types"
author = "authors"

[markup]
_merge = "deep"

[related]
threshold = 80
includeNewer = true
toLower = true

  [[related.indices]]
  name = "tags"
  weight = 100

  [[related.indices]]
  name = "categories"
  weight = 70

[security]
_merge = "deep"
enableInlineShortcodes = true

[sitemap]
_merge = "deep"

[minify]
_merge = "deep"

# Navigation
  [params.navigation]
    #other stuff
    logo = "logo.png"